<wsdl:description>

	<!-- LarKC binding (do not change) -->
	<wsdl:binding 
		name="larkcbinding" type="http://larkc.eu/wsdl-binding" />
	
	<!-- LarKC plug-in interface -->
	<wsdl:interface 
		name="Plugin"
		sawsdl:modelReference="http://larkc.eu/plugin#${larkcPluginName}">
	</wsdl:interface>
	
	<!-- Define service -->
	<wsdl:service 
		name="urn:${package}.${larkcPluginName}" interface="Plugin"
		sawsdl:modelReference="http://larkc.eu/plugin#${larkcPluginName}" >
		
    	<wsdl:endpoint location="java:${package}.${larkcPluginName}" />
	</wsdl:service>
</wsdl:description>
