<wsdl:description>
<wsdl:interface name="Plugin"
	sawsdl:modelReference="http://larkc.eu/plugin">
</wsdl:interface>
<wsdl:binding name="larkcbinding" type="http://larkc.eu/wsdl-binding" />
<!-- SPECIFIC TO THIS PLUGIN_TYPE -->
<wsdl:service name="urn:eu.larkc.plugin.LLDReasoner" interface="Plugin"
sawsdl:modelReference="http://larkc.eu/plugin#LLDReasoner" >
    <wsdl:endpoint location="java:eu.larkc.plugin.LLDReasoner" />
</wsdl:service>
</wsdl:description>
