<wsdl:description>
	<!-- COMMON TO ALL Plugin -->
	<wsdl:interface name="identifier"
		sawsdl:modelReference="http://larkc.eu/plugin#Identifier">
	</wsdl:interface>
	
	<wsdl:binding name="larkcbinding" type="http://larkc.eu/wsdl-binding" />

	<!-- SPECIFIC TO THIS Plugin -->
    <wsdl:service name="urn:eu.larkc.plugin.identifier.SindiceTriplePatternIdentifier" interface="identifier"
  	sawsdl:modelReference="http://larkc.eu/plugin#SindiceTriplePatternIdentifier" >
	    <wsdl:endpoint location="java:eu.larkc.plugin.identify.sindice.SindiceTriplePatternIdentifier" />
    </wsdl:service>

</wsdl:description>