<wsdl:description>
	<!-- COMMON TO ALL IDENTIFIERS -->
	<wsdl:interface name="identifier"
		sawsdl:modelReference="http://larkc.eu/plugin#Identifier">
	</wsdl:interface>
	
	<wsdl:binding name="larkcbinding" type="http://larkc.eu/wsdl-binding" />

	<!-- SPECIFIC TO THIS IDENTIFIER -->
    <wsdl:service name="urn:eu.larkc.plugin.hadoop.OWLClosurePlugin" interface="identifier"
  	sawsdl:modelReference="http://larkc.eu/plugin#OWLClosurePlugin" >
	    <wsdl:endpoint location="java:eu.larkc.plugin.hadoop.OWLClosurePlugin" />
    </wsdl:service>

</wsdl:description>
