<wsdl:description>

	<!-- LarKC binding (do not change) -->
	<wsdl:binding 
		name="larkcbinding" type="http://larkc.eu/wsdl-binding" />
	
	<!-- LarKC plug-in interface -->
	<wsdl:interface 
		name="Plugin"
		sawsdl:modelReference="http://larkc.eu/plugin#NQuadsToNTriples">
	</wsdl:interface>
	
	<!-- Define service -->
	<wsdl:service 
		name="urn:eu.larkc.plugin.nquadstontriples.NQuadsToNTriples" interface="Plugin"
		sawsdl:modelReference="http://larkc.eu/plugin#NQuadsToNTriples" >
		
    	<wsdl:endpoint location="java:eu.larkc.plugin.nquadstontriples.NQuadsToNTriples" />
	</wsdl:service>
</wsdl:description>
